### ISSUE TITLE
Available on the JavaScript Registry

### ISSUE THREAD

**Issue by mxdvl** [lumeland/imagemagick-deno#18]
Will this package be published to JSR?

**Comment by oscarotero** [comment]
I'm not fan of JSR and some of its design decisions, so I don't have plans to move there for now.

**Comment by oscarotero** [comment]
That being said, this package has changed over time and now it's just a wrapper to easily load the original NPM package. If you don't want to use HTTP imports, it's perfectly possible to import directly the NPM package.
The code is very simple: https://github.com/lumeland/imagemagick-deno/blob/main/mod.ts

**Comment by mxdvl** [comment]
Wonderful, [thanks to your pointers I was able to use it directly here](https://github.com/CSS-Next/logo.css/pull/21/commits/e8587161e82d8c3c79cc55b360a13e59ebcad9ff)!
