### ISSUE TITLE
Overload needed when using read with `color, width, height, (for settings)`

### ISSUE THREAD

**Issue by reggi** [lumeland/imagemagick-deno#4]
I suggest adding an optional forth argument when these are in use for `MagickReadSettings`. 

`color, width, MagickReadSettings, callback`
`color, width, height, MagickReadSettings, callback`

When width is provided without height just set height to the width for square 🤷

**Comment by oscarotero** [comment]
Hi.
Thanks but this repo only contains the same code as https://github.com/dlemstra/magick-wasm but with some modifications to make it work on Deno. So you should open the issue in the original repository.

**Comment by reggi** [comment]
@oscarotero yeah I had a feeling that was the case, sorry for opening all these up, feel free to close them.
