### ISSUE TITLE
Issue on macos

### ISSUE THREAD

**Issue by Sn0wAlice** [lumeland/imagemagick-deno#7]
```
/Users/alice/Downloads/imagemagick-deno/deno/src/magick-image.ts
Checked 87 files
error: The module's source code could not be parsed: Expected unicode escape at file:///Users/alice/Downloads/imagemagick-deno/deno/src/wasm/magick_native.js:1:1

  \nexport default MagickNative;
  ~
```

**Comment by oscarotero** [comment]
I have macos and don't have this problem. Are you able to run this script? https://github.com/lumeland/imagemagick-deno/blob/main/test/test.ts

**Comment by Sn0wAlice** [comment]
i can't, i have the same error:

```
error: The module's source code could not be parsed: Expected unicode escape at file:///Users/alice/Downloads/imagemagick-deno/deno/src/wasm/magick_native.js:1:1

  \nexport default MagickNative;
```

**Comment by oscarotero** [comment]
Seems like you are importing it from your local filesystem. Can you import it from the deno.land/x repository?
https://deno.land/x/imagemagick_deno@0.0.24

**Comment by Sn0wAlice** [comment]
Ok i found the issue: i wan calling the old `initializeImageMagick` and not the new `initialize` function :)

Seems to work now.

Thank you for your help !
