### ISSUE TITLE
Please update to include new DrawableTextKerning?

### ISSUE THREAD

**Issue by reggi** [lumeland/imagemagick-deno#8]
Can you please update the magick-image dependency to include the most recent changes?

**Comment by reggi** [comment]
For some reason they never cut a new release after 0.0.22 i forked my own https://github.com/reggi/imagemagick-deno understanable if you're gonna wait

**Comment by oscarotero** [comment]
I think I prefer to wait. There are recent changes after your fork so probably there is something not finished yet.

**Comment by oscarotero** [comment]
I just upgraded to 0.0.22.
